Changed fedramp check away from reconciler, anonymized alert details …
openshift/configure-alertmanager-operator pull request #218
Opened 2022-03-16 16:44 UTC by luis-falcon

Changed fedramp check away from reconciler, anonymized alert details for fedramp clusters

2022-03-25 19:24 UTC, blrm requested changes
I made one comment about removing one more field that includes PII but aside from that, this looks great!

2022-03-28 12:58 UTC, blrm approved these changes

2022-03-28 13:01 UTC, blrm commented
/lgtm 

/assign @cblecker

2022-03-28 14:17 UTC, fahlmant commented on pkg/controller/secret/secret_controller.go
> +	if config.IsFedramp() {
Going with my above comment, there could be one template for standard clusters and one template for fedramp clusters.

2022-03-28 21:14 UTC, fahlmant commented on pkg/controller/secret/secret_controller.go
> +	if config.IsFedramp() {
No I mean a different file. Then if fedramp, load the fedramp version of the file

2022-03-29 18:57 UTC, fahlmant approved these changes
/approve

2022-03-29 19:01 UTC, merged