Provide console URL into PD alerts
openshift/configure-alertmanager-operator pull request #99
Opened 2020-09-07 20:00 UTC by cblecker

This grabs the console URL from the system configmap (same thing `oc` does here: https://github.com/openshift/oc/blob/f2a4a0375cc7b0eacb5467a0214303983e1151d6/pkg/cli/whoami/whoami.go#L115-L130) and then puts it into the alert configuration.

2020-09-07 20:01 UTC, cblecker commented
/hold
Holding for discussion

2020-09-07 20:10 UTC, cblecker commented
Reviewing the test coverage report, the misses are just negative error checking. This should be safe to merge.

2020-09-07 22:40 UTC, cblecker commented
Found an issue in testing:
Because of the way the caching client was set up, it wasn't able to grab the configmap from `openshift-config-managed`. Made some changes to allow it to read this. I don't know how I feel about them though

2020-09-07 22:42 UTC, cblecker commented
Example of how this looks in the PD UI:
![example PD alert UI](https://user-images.githubusercontent.com/1431969/92419176-a48a5c80-f120-11ea-9319-fbf34319903e.png)

2020-09-08 13:29 UTC, jewzaam requested changes

2020-09-08 13:29 UTC, jewzaam commented on pkg/controller/secret/secret_controller.go
> +	}
If we're not able to get the console URL it shouldn't block configuration of alertmanager.  We can still get stuff done, we just are not quite as efficient.  But not having alerts configured is a big problem.  Recommend we simply ignore the error and set consoleUrl to something that won't cause the config to blow up.

2020-09-08 14:37 UTC, jewzaam commented
Similar to https://github.com/openshift/configure-alertmanager-operator/pull/98 and expect some conflicts, please work with @NautiluX on how you want to merge these.

2020-09-08 15:08 UTC, NautiluX commented
> Similar to #98 and expect some conflicts, please work with @NautiluX on how you want to merge these.

As mentioned on Slack I think both PRs provide value. Happy to rebase mine after this is merged.

2020-09-08 15:08 UTC, NautiluX commented
/lgtm

2020-09-08 20:12 UTC, cblecker commented
@jewzaam Addressed comments

2020-09-09 09:29 UTC, NautiluX reviewed
/lgtm

2020-09-09 17:03 UTC, cblecker commented
/hold cancel

2020-09-09 17:06 UTC, merged